### ISSUE TITLE
Change Request: Add support for config comments

### ISSUE THREAD

**Issue by nzakas** [eslint/json#21]
### Environment

ESLint version: HEAD
@eslint/json version: HEAD
Node version: 
npm version: 
Operating System:

### What problem do you want to solve?

The JSON plugin currently does not support configuration comments.

### What do you think is the correct solution?

Implement configuration comments using the [`ConfigCommentParser`](https://github.com/eslint/rewrite/blob/main/packages/plugin-kit/src/config-comment-parser.js) utility. These would only apply in JSONC and JSON5, but we should support all of these:

```jsonc
/* eslint rule: off */
/* eslint-disable rule */
/* eslint-enable rule */
/* eslint-disable-line rule */
/* eslint-disable-next-line rule */
```

The logic should be similar to [the JS logic](https://github.com/eslint/eslint/blob/d1f0831bac173fe3e6e81ff95c5abdbf95b02b65/lib/languages/js/source-code/source-code.js#L1028)

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

Looking for a volunteer to implement this.

**Comment by mdjermanovic** [comment]
I'd like to work on this.

**Comment by mdjermanovic** [comment]
Working on this now.

**Comment by mdjermanovic** [comment]
> /* eslint rule: off */

Just `off` or any rule configuration comments? E.g., `/* eslint json/no-duplicate-keys: "error" */`

**Comment by nzakas** [comment]
Any rule configuration comments. I was just too lazy to provide more examples. :smile:
