### ISSUE TITLE
Docs: There are not Spanish documentation

### ISSUE THREAD

**Issue by Byron2016** [eslint/json#34]
### Docs page(s)

./README.md 

### What documentation issue do you want to solve?

./README.md file has not Spanish documentation.

### What do you think is the correct solution?

Create a Spanish README.md file

### Participation

- [x] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Thanks for the proposal, but I'm not sure if we can accept it.

We are working on the design for a website to host documentation for plugins maintained by the ESLint team, including this one. I think the translations would rather be on that site than in READMEs.

Regarding translations in general, I think the biggest problem is maintenance: whenever we want to update the documentation (e.g., to document some new features), it would need to be done in all translations, which I'm not sure we can afford. 

@eslint/eslint-tsc thoughts about this?

**Comment by Byron2016** [comment]
@mdjermanovic what I finally do was to create a new repository with translations, maybe it could be util for some one. 👌
[@eslint/json](https://github.com/Byron2016/052_eslint_translations)
