### ISSUE TITLE
New Rule: indent

### ISSUE THREAD

**Issue by LJNeon** [eslint/json#39]
### Rule details

Should function similarly to the indent rule for JavaScript.

### What type of rule is this?

Suggests an alternate way of doing something

### Example code

There are many different standard indentations:
1. No whitespace
```json
{"a":5,"b":true}
```
2. Tabs
```json
{
	"a": 5,
	"b": true
}
```
3. Two-space
```json
{
  "a": 5,
  "b": true
}
```
4. Four-space
```json
{
    "a": 5,
    "b": true
}
```
and so on.

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

### Additional comments

Could easily follow the standard set by `JSON.stringify()`s [`space` option](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#space). If that doesn't seem like a good idea, then could follow the standard set by eslint's [`indent` rule](https://eslint.style/rules/js/indent).

**Comment by aladdin-add** [comment]
hi, thanks for the PR!  however, formatting-rules have been deprecated in eslint (https://eslint.org/blog/2023/10/deprecating-formatting-rules/). We might want to follow the same strategy here.

**Comment by nzakas** [comment]
We're not going to be adding formatting rules to this package. Please use a formatter like [Prettier](https://prettier.io) for this purpose.
