### ISSUE TITLE
Change Request: Correct types for `configs`

### ISSUE THREAD

**Issue by burtek** [eslint/json#52]
### Environment

ESLint version: 9.14.0
@eslint/json version: 0.6.0
Node version: 20.9.0
npm version: 10.1.0
Operating System: LMDE 6, kernel 6.1.0-26-amd64

### What problem do you want to solve?

The json plugin typings is wrong as it exports `config` property as `{}`
![Image](https://github.com/user-attachments/assets/5a8bc373-8e24-49b0-a343-3dfcec17818c)
This causes errors in IDE:
![Image](https://github.com/user-attachments/assets/99677ae5-f5ae-43e4-84be-a691ed62412f)

### What do you think is the correct solution?

The `configs` property of the plugin should be typed correctly.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by fasttime** [comment]
Thanks for reporting this problem @burtek. I can confirm that the `configs` property of the plugin is currently typed as an empty object. I've submitted a pull request that shoul fix the types: #59.

**Comment by fasttime** [comment]
@burtek yes, we should fix also [eslint/markdown](https://github.com/eslint/markdown/) and [eslint/css](https://github.com/eslint/css/). I'll take care of that.
