### ISSUE TITLE
More RFC 8259 nits

### ISSUE THREAD

**Issue by hildjj** [eslint/json#68]
### Rule details

Check as many of the constraints from RFC 8259 marked "interoperable in the sense"

### What type of rule is this?

Warns about a potential problem

### Example code

```jsonc
- Invalid top-level: `"foo"`
- Outside float64 (will parse as 0): `[1e-325]`
- Subnormal warning: `[4.94e-324]` 
- Too-large integer: `[18014398509481985]`
- Duplicate key (just needs a test): `{"a\\b": 0, "a\u005Cb": 1}`
```

### Participation

- [x] I am willing to submit a pull request to implement this rule.

### Additional comments

RFC 8259 marks several potential interoperability issues with "interoperable in the sense":

- Only an object or array at the top level.  This is the most controversial of these.
- Unique keys (already handled by `no-duplicate-keys`)
- Not order-dependent (not lintable, unless we wanted there to be another rule that enforced order, I suppose)
- (Implied in 8259) Floats should fit into a double.  Support for sub-normals should likely be optional.
- Integers in the range in the range [-(2**53)+1, (2**53)-1].  Note that `no-unsafe-values` currently will not catch integers outside that range that have not gotten all the way to being +/-Infinity. 
- Valid Unicode.  `no-unsafe-values` catches this now.
- No duplicate keys, including ones that differ by only Unicode escapes. `no-duplicate-keys` only needs some tests added to check that "a\\b" and "a\u005Cb" are duplicates.

**Comment by nzakas** [comment]
Thanks for the feedback. I'm unclear on what it is you're suggesting. Are you saying we should update some existing rules, create new rules, etc.? Can you be more specific?

**Comment by nzakas** [comment]
Also, can you please add a link to the RFC for easy reference?

**Comment by hildjj** [comment]
[RFC8259](https://www.rfc-editor.org/rfc/rfc8259) is the current IETF description of JSON.  It is aligned with [ECMA-404](https://ecma-international.org/publications-and-standards/standards/ecma-404/), but focuses more on interoperability between systems rather than on how `JSON.parse` is implemented in ECMAscript/JavaScript.

Here are more explicit recommendations:
- new rule: `top-level-composite`, which checks that the top-level thing in a JSON file is either an object or an array.  This might be off in the default config.
- `no-unsafe-values` should check for integers out of range, floats out of range, and warn on subnormals (by default).
- Add a test for escaped characters in no-duplicate-keys.test.js

Sorry I wasn't more clear before.

**Comment by nzakas** [comment]
Got it, thanks. These all seem like good additions to me. 

Only question is the naming of `top-level-composite`, as I'm not sure it communicates the intent. Maybe `interopable-top-level` instead?

**Comment by hildjj** [comment]
`interopable-top-level` works fine for me.  Would you like me to put together a PR?

**Comment by nzakas** [comment]
Or maybe `top-level-interop` is better? (Shorter, maybe more readable?)

And yes, but if you could please do a separate PR for each task, it would be appreciated.

**Comment by hildjj** [comment]
I'm making progress on a PR.

What do we think about `-0`?  Safe for interop?

**Comment by hildjj** [comment]
Those three PRs should cover this issue.

**Comment by nzakas** [comment]
> What do we think about `-0`?
> Safe for interop?

Good question. It's definitely not a problem in JavaScript, but I'm unsure of other languages.

**Comment by hildjj** [comment]
I think this is now fixed.  Suggest closing?

**Comment by nzakas** [comment]
Yes, thanks so much.
